refactor: improve assert function for checking exit code and outputs

diff --git a/bin/bgen b/bin/bgen
--- a/bin/bgen
+++ b/bin/bgen
@@ -202,6 +202,7 @@ read_project_meta() {
         fi
 
         if [[ "$PWD" == "/" ]]; then
+            cd "$project_root" || return
             break
         fi
 
@@ -742,25 +743,6 @@ build_tests_to_stdout() {
 		#!/usr/bin/env bash
 		# shellcheck disable=SC2034
 		
-		assert_exits_with_code() {
-		    local expected_code="$1"
-		    shift
-		
-		    local err
-		    ("$@") || err=$?
-		
-		    if ((err == expected_code)); then
-		        return 0
-		    fi
-		
-		    echo "assert_status: expected exit_code to be $expected_code", got "${err:-0}" >&2
-		
-		    # save line at which this happened, used later for reporting
-		    __bgen_assert_line="${BASH_LINENO[0]-}"
-		
-		    return 1
-		}
-		
 		assert_eq() {
 		    local left="$1"
 		    local right="$2"
@@ -777,6 +759,90 @@ build_tests_to_stdout() {
 		    return 1
 		}
 		export -f assert_eq
+		
+		assert_exits_with() {
+		    local args=()
+		
+		    unset __bgen_assert_code
+		    unset __bgen_assert_stdout
+		    unset __bgen_assert_stderr
+		
+		    while (($#)); do
+		        case "$1" in
+		        --code)
+		            local __bgen_assert_code=$2
+		            shift 2
+		            ;;
+		        --code=*)
+		            local __bgen_assert_code=${1#--code=}
+		            shift
+		            ;;
+		        --stdout)
+		            local __bgen_assert_stdout=$2
+		            shift 2
+		            ;;
+		        --stdout=*)
+		            local __bgen_assert_stdout=${1#--stdout=}
+		            shift
+		            ;;
+		        --stderr)
+		            local __bgen_assert_stderr=$2
+		            shift 2
+		            ;;
+		        --stderr=*)
+		            local __bgen_assert_stderr=${1#--stderr=}
+		            shift
+		            ;;
+		        --)
+		            shift
+		            args+=("$@")
+		            shift $#
+		            ;;
+		        *)
+		            args+=("$1")
+		            shift
+		            ;;
+		        esac
+		    done
+		
+		    local stderr_file
+		    stderr_file=$(mktemp)
+		
+		    local err=0
+		    local stdout
+		    stdout=$("${args[@]}" 2>"$stderr_file") || err=$?
+		
+		    local stderr
+		    stderr=$(<"$stderr_file")
+		    rm "$stderr_file"
+		
+		    local report=()
+		
+		    if [[ "${__bgen_assert_code+x}" ]] && ((__bgen_assert_code != err)); then
+		        report+=("$(printf "expected exit code: %s\nreturned exit code: %s\n" "$__bgen_assert_code" "$err")")
+		    fi
+		
+		    if [[ "${__bgen_assert_stdout+x}" ]] && [[ "$__bgen_assert_stdout" != "$stdout" ]]; then
+		        report+=("$(printf "expected stdout: %s\nreturned stdout: %s\n" "$__bgen_assert_stdout" "$stdout")")
+		    fi
+		
+		    if [[ "${__bgen_assert_stderr+x}" ]] && [[ "$__bgen_assert_stderr" != "$stderr" ]]; then
+		        report+=("$(printf "expected stderr: %s\nreturned stderr: %s\n" "$__bgen_assert_stderr" "$stderr")")
+		    fi
+		
+		    if ((${#report[@]})); then
+		        printf 'assert_exits_with failed:\n' >&2
+		        printf '%s\n' "${report[@]}" >&2
+		
+		        # save line at which this happened, used later for reporting
+		        __bgen_assert_line="${BASH_LINENO[0]-}"
+		
+		        return 1
+		    fi
+		
+		    return 0
+		}
+		export -f assert_exits_with
 		BGEN_EOF_1435_24388
 # BGEN__INCLUDE_STR_END
     process_input <<<"$assertlib"
