feat: improved test running

diff --git a/bin/bgen b/bin/bgen
--- a/bin/bgen
+++ b/bin/bgen
@@ -53,6 +53,14 @@ LOG_LEVEL="${LOG_LEVEL:-6}" # 7 = debug -> 0 = emergency
 NO_COLOR="${NO_COLOR:-}"    # true = disable color. otherwise autodetected
 
 
+# BGEN__SHEBANG_REMOVED
+
+# BGEN__BEGIN build.sh
+# BGEN__SHEBANG_REMOVED
+
+# BGEN__BEGIN utils.sh
+# BGEN__SHEBANG_REMOVED
+
 bail() {
     local err_message="$1"
     local err_code="${2:-1}"
@@ -64,7 +72,7 @@ bail() {
 trim_str() {
     echo "$1" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
 }
-
+# BGEN__END utils.sh
 
 build_project() {
     # save it in a temp file first
@@ -96,7 +104,6 @@ build_project_to_stdout() {
     # used later to keep track of whether a file was imported or not
     # declared here to be on the biggest private scope it's needed in
     local imported_files=()
-    local included_scripts=()
 
     local project_name header_file entrypoint_file entrypoint_func shebang_string imports_dir
     read_project_meta
@@ -111,7 +118,6 @@ build_tests_to_stdout() {
     # used later to keep track of whether a file was imported or not
     # declared here to be on the biggest private scope it's needed in
     local imported_files=()
-    local included_scripts=()
 
     local project_name header_file tests_dir shebang_string imports_dir
     read_project_meta
@@ -124,31 +130,156 @@ build_tests_to_stdout() {
     echo_header
     for test_file in "$tests_dir"/*; do
         [[ -f "$test_file" ]] || continue
-        process_file "$test_file"
-
-        local testfile="${test_file/$tests_dir\//}"
-        local testfuncs=($( shfmt -tojson <"$test_file" | jq -Mr "$jq_query"))
-
-        if [[ " ${testfuncs[*]} " == *" before_all "* ]]; then
-            echo "echo '$testfile::before_all'"
-            echo "before_all"
-            echo
-        fi
-
-        for func in "${testfuncs[@]}"; do
-            [[ "$func" =~ ^(before|after)_all$ ]] && continue
-
-            echo "echo '$testfile::$func'"
-            echo "$func"
-            echo
-        done
-
-        if [[ " ${testfuncs[*]} " == *" after_all "* ]]; then
-            echo "echo '$testfile::after_all'"
-            echo "after_all"
-            echo
-        fi
+        bgen_import "$test_file"
     done
+
+# BGEN__INCLUDE_STR_BEGIN
+    testlib=$(
+    cat <<-"EOF"
+		#!/usr/bin/env bash
+		
+		__test_failed=()
+		__test_report=()
+		
+		# shellcheck disable=SC2120
+		__get_source_line() {
+		    local stack="${1:-0}"
+		
+		    local bgen_line
+		    bgen_line=$((1 + ${BASH_LINENO[$((stack + 1))]}))
+		
+		    local line_file=
+		    local line_nr=0
+		    while IFS= read -r line; do
+		        local current_line_nr
+		        current_line_nr=$(awk '$2 == "BGEN__BEGIN" {printf $1}' <<<"$line")
+		
+		        [[ "$current_line_nr" ]] || continue
+		        ((bgen_line > current_line_nr)) || continue
+		
+		        line_file="$(awk '{OFS=""; $1=""; $2=""; printf $0 }')"
+		        line_nr=$((current_line_nr + 1))
+		    done <<<"$__BGEN_LINEMAP__"
+		
+		    echo "${line_file/$PWD\//}:$((bgen_line - line_nr)):"
+		}
+		export -f __get_source_line
+		
+		assert_status() {
+		    local status_code="$?"
+		
+		    local expected_code="${1:-}"
+		    [[ "${2:-}" ]] && status_code="$2"
+		
+		    [[ "$status_code" == "$expected_code" ]] && return 0
+		
+		    __get_source_line >&2
+		    echo "Expected status code to be $expected_code, got: $status_code" >&2
+		    exit 1
+		}
+		export -f assert_status
+		
+		assert_eq() {
+		    local left="$1"
+		    local right="$2"
+		
+		    [[ "$left" == "$right" ]] && return 0
+		
+		    (   
+		        __get_source_line
+		        echo "Expected left string to match right string."
+		        echo "Left:"
+		        echo "$left"
+		        echo
+		        echo "Right:"
+		        echo "$right"
+		    ) >&2
+		    exit 1
+		}
+		export -f assert_eq
+		
+		__run_test() {
+		    local test_func="$1"
+		    local stdout_file stderr_file
+		
+		    stdout_file="$(mktemp)"
+		    # shellcheck disable=SC2064
+		    trap "rm '$stdout_file'" EXIT
+		
+		    stderr_file="$(mktemp)"
+		    # shellcheck disable=SC2064
+		    trap "rm '$stderr_file'" EXIT
+		
+		    local err=""
+		    (   
+		        # Exit on error. Append "|| true" if you expect an error.
+		        set -o errexit
+		        # Exit on error inside any functions or subshells.
+		        set -o errtrace
+		        # Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
+		        set -o nounset
+		        # Catch the error in case mysqldump fails (but gzip succeeds) in $(mysqldump | gzip)
+		        set -o pipefail
+		        # Turn on traces, useful for debugging. Set _XTRACE to enable
+		        [[ "${_XTRACE:-}" ]] && set -o xtrace
+		
+		        "$test_func" >"$stdout_file" 2>"$stderr_file"
+		    ) || err="$?"
+		
+		    if [[ ! "$err" ]]; then
+		        printf "."
+		        return
+		    fi
+		
+		    if [[ -s "$stdout_file" || -s "$stderr_file" ]]; then
+		        local report
+		        report=$(
+		            echo
+		            echo "----- $test_func -----"
+		
+		            if [[ -s "$stdout_file" ]]; then
+		                echo "stdout:"
+		                cat "$stdout_file"
+		                echo
+		            fi
+		
+		            if [[ -s "$stderr_file" ]]; then
+		                echo "stderr:"
+		                cat "$stderr_file"
+		                echo
+		            fi
+		        )
+		        __test_report+=("$report")
+		    fi
+		
+		    __test_failed+=("$test_func")
+		
+		    printf "F"
+		    return
+		}
+		
+		for __test_func in $( declare -F | awk '$3 ~ /^ *test_/ {printf "%s\n", $3}'); do
+		    __run_test "$__test_func"
+		done
+		echo
+		
+		if (("${#__test_failed[@]}")); then
+		    echo
+		    echo "failed tests:"
+		    for test_func in "${__test_failed[@]}"; do
+		        echo "    $test_func"
+		    done
+		fi
+		
+		if (("${#__test_report[@]}")); then
+		    for test_report in "${__test_report[@]}"; do
+		        echo "$test_report"
+		    done
+		fi
+		EOF
+    )
+# BGEN__INCLUDE_STR_END
+    echo "$testlib"
 }
 
 # shellcheck disable=SC2034
@@ -227,6 +358,7 @@ echo_header() {
         process_file "$header_file"
     else
         local default_header
+# BGEN__INCLUDE_STR_BEGIN
         default_header=$(
         cat <<-"EOF"
 			#!/bin/bash
@@ -284,6 +416,7 @@ echo_header() {
 			NO_COLOR="${NO_COLOR:-}"    # true = disable color. otherwise autodetected
 			EOF
         )
+# BGEN__INCLUDE_STR_END
 
         echo "$default_header"
     fi
@@ -303,18 +436,16 @@ process_file() {
 
     local found_first_line=
     while IFS= read -r line; do
-        # process source directives that point ot static files
+        # Process source directives that point ot static files
         process_directive "$line" || { check && continue; }
 
-        # remove first shebang in the file
+        # Remove first shebang in the file
         if ! [[ "$found_first_line" ]]; then
             process_shebang "$line" || { check && continue; }
         fi
 
         if [[ ! "$found_first_line" ]]; then
-            if echo "$line" | grep -E "^[[:space:]]*$" >/dev/null; then
-                continue
-            else
+            if ! echo "$line" | grep -E "^[[:space:]]*$" >/dev/null; then
                 found_first_line=1
             fi
         fi
@@ -329,7 +460,7 @@ process_file() {
 echo_entrypoint_call() {
     if [[ "$entrypoint_func" ]]; then
         # shellcheck disable=SC2016
-        printf '[[ "$__main__" ]] && %s "$@"\n\n' "$entrypoint_func"
+        printf '\n[[ "$__main__" ]] && %s "$@"\n' "$entrypoint_func"
     fi
 }
 
@@ -352,6 +483,8 @@ process_shebang() {
     line=$(trim_str "$line")
 
     if [[ "$line" =~ ^\#\! ]]; then
+        found_first_line=1
+        echo "# BGEN__SHEBANG_REMOVED"
         return 200
     fi
 }
@@ -390,6 +523,12 @@ process_directive() {
 find_source_file() {
     local file="${1:-}"
 
+    # If the file exists, return it
+    if [[ -f "$file" ]]; then
+        echo "$file"
+        return
+    fi
+
     # Check if there exists a file with `.sh` appended to it
     if [[ -f "${file}.sh" ]]; then
         echo "${file}.sh"
@@ -418,7 +557,7 @@ bgen_import() {
     # Raise error if file does not exit
     source_file=$(find_source_file "${1:-}")
     if [[ ! -f "$source_file" ]]; then
-        bail "bgen:import error: cannot import '$file'"
+        bail "bgen import error: cannot import '$file'"
     fi
 
     # Don't re-import file if it was already imported
@@ -426,11 +565,14 @@ bgen_import() {
         # Mark file as imported
         imported_files+=("$(realpath "$source_file")")
 
+        # Add a comment indicating where the processing starts
+        echo "# BGEN__BEGIN $source_file"
+
         # Do normal file processing
         process_file "$source_file"
 
-        # Add some spacing
-        printf '\n\n'
+        # Add a comment indicating where the processing starts
+        echo "# BGEN__END $source_file"
     fi
 
     # Return 200 to tell check() that we've processed something
@@ -455,6 +597,7 @@ bgen_include_str() {
         bail "bgen:include_str error: cannot import $file"
     fi
 
+    echo "# BGEN__INCLUDE_STR_BEGIN"
     echo "${indent}${variable}=\$("
     echo "${indent}cat <<-\"EOF\""
     while IFS= read -r line; do
@@ -462,6 +605,7 @@ bgen_include_str() {
     done <"$file"
     echo "${indent_plus}EOF"
     echo "${indent})"
+    echo "# BGEN__INCLUDE_STR_END"
 
     # Return 200 to tell check() that we've processed something
     return 200
@@ -483,6 +627,9 @@ is_in_array() {
 is_declared() {
     declare -p "$@" >/dev/null 2>/dev/null
 }
+# BGEN__END utils.sh
+# BGEN__BEGIN run.sh
+# BGEN__SHEBANG_REMOVED
 
 
 run_project() {
@@ -494,22 +641,28 @@ debug_project() {
     export __BGEN_PIPE_SOURCE__="${__base__:-$0} debug"
     bash -x -c "$(build_project_to_stdout)" "${__base__:-$0} run" "$@"
 }
+# BGEN__END build.sh
+# BGEN__BEGIN test.sh
+# BGEN__SHEBANG_REMOVED
 
 
 test_debug_project() {
-    # TODO: Check for shfmt and jq
-
     export __BGEN_PIPE_SOURCE__="${__base__:-$0} test"
     build_tests_to_stdout
 }
 
 test_project() {
-    # TODO: Check for shfmt and jq
+    # TODO: Check awk exists
+
+    local test_code linemap
+    test_code="$(build_tests_to_stdout)"
+    linemap="$(awk '$0 ~ /^# BGEN__/ {OFS=""; $1=""; $2=$2 " "; print NR " " $0}' <<<"$test_code")"
 
     export __BGEN_PIPE_SOURCE__="${__base__:-$0} test"
-    bash -c "$(build_tests_to_stdout)" "${__base__:-$0} test" "$@"
+    export __BGEN_LINEMAP__="$linemap"
+    bash -c "$test_code" "${__base__:-$0} test" "$@"
 }
-
+# BGEN__END build.sh
 
 # entrypoint
 main() {
@@ -544,5 +697,5 @@ main() {
 
     build_project_to_stdout
 }
-[[ "$__main__" ]] && main "$@"
 
+[[ "$__main__" ]] && main "$@"
