feat: failed tests now cause testrunner to return non-zero exit code

diff --git a/bin/bgen b/bin/bgen
--- a/bin/bgen
+++ b/bin/bgen
@@ -441,6 +441,11 @@ build_tests_to_stdout() {
 		        echo "$test_report"
 		    done
 		fi
+		
+		# exit with error if any test failed
+		if (("${#__test_failed[@]}")); then
+		    exit 1
+		fi
 		EOF
     )
 # BGEN__INCLUDE_STR_END
