feat: allow showing output of passing tests

diff --git a/bin/bgen b/bin/bgen
--- a/bin/bgen
+++ b/bin/bgen
@@ -130,7 +130,8 @@ build_tests_to_stdout() {
 
     local test_files=()
     local test_funcs=()
-    local failed=
+    local failed=0
+    local no_capture="${BGEN_NO_CAPTURE:-0}"
     while (($#)); do
         case "$1" in
         -k)
@@ -139,6 +140,10 @@ build_tests_to_stdout() {
             ;;
         -k=*)
             test_funcs+=("${1/-k=/}")
+            shift
+            ;;
+        -C | --no-capture)
+            no_capture=1
             shift
             ;;
         *)
@@ -156,7 +161,7 @@ build_tests_to_stdout() {
         esac
     done
 
-    if [[ "$failed" ]]; then
+    if ((failed)); then
         exit 1
     elif ! ((${#test_files[@]})); then
         for file in "$tests_dir"/*; do
@@ -182,6 +187,8 @@ build_tests_to_stdout() {
         echo "\$(declare -F | awk '\$3 ~ /^ *test_/ {printf \"%s\n\", \$3}')"
     fi
     echo ")"
+
+    echo "BGEN_NO_CAPTURE=$no_capture"
 
 # BGEN__INCLUDE_STR_BEGIN
     testlib=$(
@@ -337,7 +344,7 @@ build_tests_to_stdout() {
 		
 		    [[ "$left" == "$right" ]] && return 0
 		
-		    (   
+		    (
 		        echo "assert_eq expected:"
 		        echo "$left"
 		        echo
@@ -360,13 +367,19 @@ build_tests_to_stdout() {
 		    # shellcheck disable=SC2064
 		    trap "rm '$stderr_file'" EXIT
 		
+		    # we don't want this subshell to cause the entire test to fail
+		    # so we relax bash options until we get a status code
 		    set +o errexit +o errtrace +o nounset +o pipefail
-		    (   
+		    (
+		        # set up some hooks to print original error lines and files
 		        trap '__handle_debug "$?" "$LINENO" "$BASH_COMMAND"' DEBUG
 		        trap 'trap - DEBUG; __handle_error "$LINENO"' ERR
 		        trap 'trap - DEBUG; __handle_exit "$LINENO"' EXIT
+		
+		        # enable some bash options to allow error checking
 		        set -o errexit -o errtrace -o nounset -o pipefail -o functrace
 		
+		        # call our test function
 		        "$test_func"
 		
 		        # workaround to check if function didn't end prematurely
@@ -376,8 +389,16 @@ build_tests_to_stdout() {
 		    local err=$?
 		    set -o errexit -o errtrace -o nounset -o pipefail
 		
-		    if [[ ! "${PRINT_ALL-}" && "$err" == 0 ]]; then
+		    # print a dot or F depending on test status
+		    if ((err)); then
+		        printf "%bF%b" "$__COL_DANGER" "$__COL_RESET"
+		        __test_failed+=("$test_func")
+		    else
 		        printf "%b.%b" "$__COL_SUCCESS" "$__COL_RESET"
+		    fi
+		
+		    : "${BGEN_NO_CAPTURE:=}"
+		    if ! ((err || BGEN_NO_CAPTURE)); then
 		        return
 		    fi
 		
@@ -400,11 +421,6 @@ build_tests_to_stdout() {
 		        )
 		        __test_report+=("$report")
 		    fi
-		
-		    __test_failed+=("$test_func")
-		
-		    printf "%bF%b" "$__COL_DANGER" "$__COL_RESET"
-		    return
 		}
 		
 		# look over test functions
