fix: correct test related issues

diff --git a/dist/bgen b/dist/bgen
--- a/dist/bgen
+++ b/dist/bgen
@@ -169,19 +169,22 @@ read_project_meta() {
     butl.is_declared import_paths || local import_paths
 
     # make sure some vars are local if not declared on a parent scope
-    butl.is_declared project_root || local project_root
-    butl.is_declared project_name || local project_name
-    butl.is_declared header_file || local header_file
-    butl.is_declared entrypoint_file || local entrypoint_file
-    butl.is_declared entrypoint_func || local entrypoint_func
-    butl.is_declared shebang_string || local shebang_string
-    butl.is_declared output_file || local output_file
-    butl.is_declared tests_dir || local tests_dir
+    butl.is_declared project_root || local project_root=
+    butl.is_declared project_name || local project_name=
+    butl.is_declared header_file || local header_file=
+    butl.is_declared entrypoint_file || local entrypoint_file=
+    butl.is_declared entrypoint_func || local entrypoint_func=
+    butl.is_declared source_dir || local source_dir=
+    butl.is_declared shebang_string || local shebang_string=
+    butl.is_declared tests_dir || local tests_dir=
+    butl.is_declared output_file || local output_file=
+    butl.is_declared output_dir || local output_dir=
+    butl.is_declared is_library || local is_library=
 
     # set some defaults
-    entrypoint_file="src/main.sh"
     shebang_string="#!/usr/bin/env bash"
     tests_dir="tests"
+    output_dir="dist"
 
     local import_paths_extra=()
     import_paths=()
@@ -209,6 +212,29 @@ read_project_meta() {
         cd ..
     done
 
+    # If there's a lib/ directory, but no src/ directory, assume it's a library
+    if [[ ! "$is_library" && -d "lib" && ! -d "src" ]]; then
+        is_library=1
+    fi
+
+    # source directory is lib for libraries and src for single script files
+    if [[ ! "$source_dir" ]]; then
+        if ((is_library)); then
+            source_dir="lib"
+        else
+            source_dir="src"
+        fi
+    fi
+
+    # set the default entrypoint file
+    if [[ ! "$entrypoint_file" ]]; then
+        if ((is_library)); then
+            entrypoint_file=""
+        else
+            entrypoint_file="${source_dir%/}/main.sh"
+        fi
+    fi
+
     # set default project name
     if [[ ! "${project_name:-}" ]]; then
         # ${file##*/} keeps only what's after the last slash (aka the basename)
@@ -217,12 +243,20 @@ read_project_meta() {
 
     # set default output file
     if [[ ! "${output_file:-}" ]]; then
-        output_file="bin/$project_name"
+        if ((is_library)); then
+            output_file=""
+        else
+            output_file="${output_dir%/}/${project_name#/}"
+        fi
     fi
 
     # set default entrypoint function
     if [[ ! "${entrypoint_func:-}" ]]; then
-        entrypoint_func="$project_name"
+        if ((is_library)); then
+            entrypoint_func=""
+        else
+            entrypoint_func="$project_name"
+        fi
     fi
 
     # add the extra import paths
@@ -692,6 +726,8 @@ build_tests_to_stdout() {
     local tests_dir=
     local entrypoint_file=
     local entrypoint_func=
+    local source_dir=
+    local is_library=
     read_project_meta
 
     if ! ((${#test_files[@]})); then
@@ -713,9 +749,32 @@ build_tests_to_stdout() {
     echo_header
 
     # pre-including the project for tests to have better coverage reports
-    # if there's no entrypoint function, we assume the entrypoint file
-    # runs actual code and that can cause problems during tests
-    if [[ "$entrypoint_func" && -s "$entrypoint_file" ]]; then
+    if ((is_library)); then
+        if shopt -qs extglob; then
+            local keep_extglob=1
+        fi
+
+        shopt -s extglob
+        for file in "${source_dir%/}"/**/*.sh; do
+            # If we have the same path as the query, then we got no file
+            if [[ "$file" == "${source_dir%/}/**/*.sh" ]]; then
+                break
+            fi
+
+            # ignore files that start with an underscore
+            if [[ "$file" == _* ]]; then
+                continue
+            fi
+
+            bgen_import "$file" || { check && true; }
+        done
+
+        if ! ((keep_extglob)); then
+            shopt -u extglob
+        fi
+    elif [[ "$entrypoint_func" && -s "$entrypoint_file" ]]; then
+        # if there's no entrypoint function, we assume the entrypoint file
+        # runs actual code and that can cause problems during tests
         bgen_import "$entrypoint_file" || { check && true; }
     fi
 
@@ -805,12 +864,28 @@ build_tests_to_stdout() {
 		        esac
 		    done
 		
+		    local err=0
+		
 		    local stderr_file
 		    stderr_file=$(mktemp)
 		
-		    local err=0
-		    local stdout
-		    stdout=$("${args[@]}" 2>"$stderr_file") || err=$?
+		    if ((BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] >= 2 && BASH_VERSINFO[1] <= 3)); then
+		        local stdout_file
+		        stdout_file=$(mktemp)
+		
+		        # Working around bash 4.2 and 4.3 not returning the correct exit code of subprocesses
+		        err=$(
+		            "${args[@]}" 1>"$stdout_file" 2>"$stderr_file"
+		            echo $?
+		        )
+		
+		        local stdout
+		        stdout=$(<"$stdout_file")
+		        rm "$stdout_file"
+		    else
+		        local stdout
+		        stdout=$("${args[@]}" 2>"$stderr_file") || err=$?
+		    fi
 		
 		    local stderr
 		    stderr=$(<"$stderr_file")
@@ -1039,12 +1114,14 @@ build_tests_to_stdout() {
 		    # prevent the exit_handler from outputting anything since it's also executed
 		    __bgen_test_error_handled=1
 		
-		    # print the original source file and line number for easy debugging
-		    local source_file=
-		    local source_line_nr=
-		    __bgen_test_get_source_line "$line_nr"
-		    printf '%b%s:%s (status: %s)%b\n' \
-		        "$__BGEN_TEST_COL_DANGER" "$source_file" "$source_line_nr" "$rc" "$__BGEN_TEST_COL_RESET" >&2
+		    if [[ "$__bgen_test_main_subshell" == "$BASH_SUBSHELL" ]]; then
+		        # print the original source file and line number for easy debugging
+		        local source_file=
+		        local source_line_nr=
+		        __bgen_test_get_source_line "$line_nr"
+		        printf '%b%s:%s (status: %s)%b\n' \
+		            "$__BGEN_TEST_COL_DANGER" "$source_file" "$source_line_nr" "$rc" "$__BGEN_TEST_COL_RESET" >&2
+		    fi
 		
 		    # exit with the same return code we came with
 		    exit "$rc"
@@ -1154,7 +1231,7 @@ build_tests_to_stdout() {
 		        local source_line_nr=
 		        local source_file=
 		        __bgen_test_get_source_line "$line_nr"
-		        printf -- '- %s %s %-4s %-4s %s %s\n' "$__bgen_test_main_subshell" "$BASH_SUBSHELL" \
+		        printf -- '%s %s %-4s %-4s %s %s\n' "$rc" "$BASH_SUBSHELL" \
 		            "$source_line_nr" "$line_nr" \
 		            "${__bgen_test_covered_lines[$line_nr]}" "$cmd" >&2
 		    fi
